# This is a basic workflow to help you get started with Actions

name: Gif Comment
on:
  issues:
    types: [opened]

jobs:
  comment:
    if: github.event.name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Funny comments
        uses: Marta83/funny-comment-action@v2.1
        id: Gifo
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
